In [25]:
import numpy as np
import pandas as pd

In [26]:
movies=pd.read_csv('movies_dataframe.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [27]:
ipl=pd.read_csv('ipl-matches_dataframe.csv')
ipl.set_index('ID',inplace=True)
ipl

,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
ID,,,,,,,,,,,,,,,,,,,
1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [5]:
#shape
print(movies.shape)
print(ipl.shape)

(1629, 18)
(950, 19)

In [6]:
#dtypes--datatype of each column
movies.dtypes

title_x                 str
imdb_id                 str
poster_path             str
wiki_link               str
title_y                 str
original_title          str
is_adult              int64
year_of_release       int64
runtime                 str
genres                  str
imdb_rating         float64
imdb_votes            int64
story                   str
summary                 str
tagline                 str
actors                  str
wins_nominations        str
release_date            str
dtype: object

In [7]:
#index
print(movies.index)
print(ipl.index)

RangeIndex(start=0, stop=1629, step=1)
Index([1312200, 1312199, 1312198, 1312197, 1304116, 1304115, 1304114, 1304113,
       1304112, 1304111,
       ...
        335991,  335990,  335989,  335988,  335987,  335986,  335985,  335984,
        335983,  335982],
      dtype='int64', name='ID', length=950)

In [8]:
#columns
print(movies.columns)
print(ipl.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')
Index(['City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2', 'Venue',
       'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam', 'WonBy',
       'Margin', 'method', 'Player_of_Match', 'Team1Players', 'Team2Players',
       'Umpire1', 'Umpire2'],
      dtype='str')

In [9]:
#values
print(movies.values)
print(ipl.values)

[['Uri: The Surgical Strike' 'tt8291224'
  'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg'
  ...
  'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|'
  '4 wins' '11 January 2019 (USA)']
 ['Battalion 609' 'tt9472208' nan ...
  'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|'
  nan '11 January 2019 (India)']
 ['The Accidental Prime Minister (film)' 'tt6986710'
  'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg'
  ...
  'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|'
  nan '11 January 2019 (USA)']
 ...
 ['Sabse Bada Sukh' 'tt0069204' nan ...
  'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|'
  nan nan]
 ['Daaka' 'tt10833860'
  'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg'
  ... 'Gippy Grewal|Zareen Khan|' nan '1 November 2019 (USA)']
 ['Humsafar' 'tt2403201'
  'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png'
  ... 'Fawad Khan|' nan 'TV Series (2011–2012)']]
[['Ahmedabad' '2022-05-29' '2022' ...
  "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']"
  'CB Gaffaney' 'Nitin Menon']
 ['Ahmedabad' '2022-05-27' '2022' ...
  "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']"
  'CB Gaffaney' 'Nitin Menon']
 ['Kolkata' '2022-05-25' '2022' ...
  "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']"
  'J Madanagopal' 'MA Gough']
 ...
 ['Delhi' '2008-04-19' '2007/08' ...
  "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']"
  'Aleem Dar' 'GA Pratapkumar']
 ['Chandigarh' '2008-04-19' '2007/08' ...
  "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']"
  'MR Benson' 'SL Shastri']
 ['Bangalore' '2008-04-18' '2007/08' ...
  "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']"
  'Asad Rauf' 'RE Koertzen']]

In [10]:
#head
print(movies.head(2))
print(ipl.head(2))

                    title_x    imdb_id  \
0  Uri: The Surgical Strike  tt8291224
1             Battalion 609  tt9472208

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609

                    title_y            original_title  is_adult  \
0  Uri: The Surgical Strike  Uri: The Surgical Strike         0
1             Battalion 609             Battalion 609         0

   year_of_release runtime            genres  imdb_rating  imdb_votes  \
0             2019     138  Action|Drama|War          8.4       35112
1             2019     131               War          4.1          73

                                               story  \
0  Divided over five chapters  the film chronicle...
1  The story revolves around a cricket match betw...

                                             summary tagline  \
0  Indian army special forces execute a covert op...     NaN
1  The story of Battalion 609 revolves around a c...     NaN

                                              actors wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...           4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...              NaN

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)
              City        Date Season  MatchNumber  \
ID
1312200  Ahmedabad  2022-05-29   2022        Final
1312199  Ahmedabad  2022-05-27   2022  Qualifier 2

                               Team1             Team2  \
ID
1312200             Rajasthan Royals    Gujarat Titans
1312199  Royal Challengers Bangalore  Rajasthan Royals

                                    Venue        TossWinner TossDecision  \
ID
1312200  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals          bat
1312199  Narendra Modi Stadium, Ahmedabad  Rajasthan Royals        field

        SuperOver       WinningTeam    WonBy  Margin method Player_of_Match  \
ID
1312200         N    Gujarat Titans  Wickets     7.0    NaN       HH Pandya
1312199         N  Rajasthan Royals  Wickets     7.0    NaN      JC Buttler

                                              Team1Players  \
ID
1312200  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1312199  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...

                                              Team2Players      Umpire1  \
ID
1312200  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...  CB Gaffaney
1312199  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...  CB Gaffaney

             Umpire2
ID
1312200  Nitin Menon
1312199  Nitin Menon

In [12]:
#tail
print(movies.tail(2))
print(ipl.tail(2))

       title_x     imdb_id                                        poster_path  \
1627     Daaka  tt10833860  https://upload.wikimedia.org/wikipedia/en/thum...
1628  Humsafar   tt2403201  https://upload.wikimedia.org/wikipedia/en/thum...

                                   wiki_link   title_y original_title  \
1627     https://en.wikipedia.org/wiki/Daaka     Daaka          Daaka
1628  https://en.wikipedia.org/wiki/Humsafar  Humsafar       Humsafar

      is_adult  year_of_release runtime         genres  imdb_rating  \
1627         0             2019     136         Action          7.4
1628         0             2011      35  Drama|Romance          9.0

      imdb_votes                                              story  \
1627          38  Shinda tries robbing a bank so he can be wealt...
1628        2968  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                         actors wins_nominations           release_date
1627  Gippy Grewal|Zareen Khan|              NaN  1 November 2019 (USA)
1628                Fawad Khan|              NaN  TV Series (2011–2012)
              City        Date   Season MatchNumber  \
ID
335983  Chandigarh  2008-04-19  2007/08           2
335982   Bangalore  2008-04-18  2007/08           1

                              Team1                  Team2  \
ID
335983              Kings XI Punjab    Chennai Super Kings
335982  Royal Challengers Bangalore  Kolkata Knight Riders

                                             Venue  \
ID
335983  Punjab Cricket Association Stadium, Mohali
335982                       M Chinnaswamy Stadium

                         TossWinner TossDecision SuperOver  \
ID
335983          Chennai Super Kings          bat         N
335982  Royal Challengers Bangalore        field         N

                  WinningTeam WonBy  Margin method Player_of_Match  \
ID
335983    Chennai Super Kings  Runs    33.0    NaN      MEK Hussey
335982  Kolkata Knight Riders  Runs   140.0    NaN     BB McCullum

                                             Team1Players  \
ID
335983  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
335982  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                             Team2Players    Umpire1  \
ID
335983  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...  MR Benson
335982  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...  Asad Rauf

            Umpire2
ID
335983   SL Shastri
335982  RE Koertzen

In [13]:
#sample
print(movies.sample(5))
print(ipl.sample(5))

                     title_x    imdb_id  \
224   Viceroy's House (film)  tt4977530
773           Double Dhamaal  tt1728239
427                Bangistan  tt3422462
1300            Socha Na Tha  tt0451919
978      Rab Ne Bana Di Jodi  tt1182937

                                            poster_path  \
224   https://upload.wikimedia.org/wikipedia/en/f/f3...
773   https://upload.wikimedia.org/wikipedia/en/thum...
427   https://upload.wikimedia.org/wikipedia/en/thum...
1300  https://upload.wikimedia.org/wikipedia/en/thum...
978   https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link              title_y  \
224       https://en.wikipedia.org/wiki/Partition:_1947      Viceroy's House
773        https://en.wikipedia.org/wiki/Double_Dhamaal       Double Dhamaal
427             https://en.wikipedia.org/wiki/Bangistan            Bangistan
1300         https://en.wikipedia.org/wiki/Socha_Na_Tha         Socha Na Tha
978   https://en.wikipedia.org/wiki/Rab_Ne_Bana_Di_Jodi  Rab Ne Bana Di Jodi

           original_title  is_adult  year_of_release runtime  \
224       Viceroy's House         0             2017     106
773        Double Dhamaal         0             2011     138
427             Bangistan         0             2015     135
1300         Socha Na Tha         0             2005     137
978   Rab Ne Bana Di Jodi         0             2008     167

                       genres  imdb_rating  imdb_votes  \
224   Biography|Drama|History          6.7        5993
773        Comedy|Crime|Drama          3.8        3105
427              Comedy|Drama          4.6         992
1300           Comedy|Romance          7.5        6878
978        Comedy|Drama|Music          7.1       40973

                                                  story  \
224   New Dehli in March 1947. The huge and stately ...
773   After losing a huge sum to a police officer  K...
427   Bangistan is a whip smart and uproarious satir...
1300  Mr. Oberoi is a wealthy industrialist  and liv...
978   Have you ever stopped to think if the most ord...

                                                summary  \
224   The final Viceroy of India  Lord Mountbatten  ...
773   Four slackers decide to avenge their humiliati...
427   Two blundering terrorists with lofty ideologie...
1300  A boy is forced meet a girl for an arranged ma...
978   A breathtaking  goose flesh igniting  awe insp...

                                                tagline  \
224                               Based on a true story
773                                                 NaN
427                                                 NaN
1300                                                NaN
978   There is an extraordinary love story in every ...

                                                 actors  \
224   Hugh Bonneville|Gillian Anderson|Manish Dayal|...
773   Sanjay Dutt|Riteish Deshmukh|Arshad Warsi|Jave...
427   Jacqueline Fernandez|Riteish Deshmukh|Michalin...
1300  Abhay Deol|Ayesha Takia|Ayesha Jhulka|Apoorva ...
978   Shah Rukh Khan|Anushka Sharma|Vinay Pathak|M.K...

             wins_nominations            release_date
224                     1 win  1 September 2017 (USA)
773      1 win & 1 nomination       1 July 2011 (USA)
427              1 nomination     7 August 2015 (USA)
1300                      NaN    4 March 2005 (India)
978   4 wins & 14 nominations  12 December 2008 (USA)
              City        Date   Season MatchNumber                Team1  \
ID
419150      Jaipur  2010-04-11  2009/10          45     Rajasthan Royals
419118   Ahmedabad  2010-03-20  2009/10          13     Rajasthan Royals
1216516        NaN  2020-10-02  2020/21          14  Sunrisers Hyderabad
392202   Centurion  2009-04-30     2009          22  Chennai Super Kings
1254071    Chennai  2021-04-21     2021          14         Punjab Kings

                         Team2                                     Venue  \
ID
419150          Mumbai Indians                    Sawai Mansingh Stadium
419118   Kolkata Knight Riders              Sardar Patel Stadium, Motera
1216516    Chennai Super Kings       Dubai International Cricket Stadium
392202        Rajasthan Royals                           SuperSport Park
1254071    Sunrisers Hyderabad  MA Chidambaram Stadium, Chepauk, Chennai

                  TossWinner TossDecision SuperOver          WinningTeam  \
ID
419150      Rajasthan Royals        field         N       Mumbai Indians
419118      Rajasthan Royals          bat         N     Rajasthan Royals
1216516  Sunrisers Hyderabad          bat         N  Sunrisers Hyderabad
392202      Rajasthan Royals        field         N  Chennai Super Kings
1254071         Punjab Kings          bat         N  Sunrisers Hyderabad

           WonBy  Margin method  Player_of_Match  \
ID
419150      Runs    37.0    NaN     SR Tendulkar
419118      Runs    34.0    NaN  AA Jhunjhunwala
1216516     Runs     7.0    NaN          PK Garg
392202      Runs    38.0    NaN         SK Raina
1254071  Wickets     9.0    NaN      JM Bairstow

                                              Team1Players  \
ID
419150   ['MJ Lumb', 'NV Ojha', 'FY Fazal', 'SR Watson'...
419118   ['MJ Lumb', 'NV Ojha', 'FY Fazal', 'AA Jhunjhu...
1216516  ['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...
392202   ['PA Patel', 'ML Hayden', 'SK Raina', 'S Badri...
1254071  ['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...

                                              Team2Players       Umpire1  \
ID
419150   ['ST Jayasuriya', 'SR Tendulkar', 'AT Rayudu',...   BR Doctrove
419118   ['MK Tiwary', 'BJ Hodge', 'CA Pujara', 'SC Gan...   RE Koertzen
1216516  ['F du Plessis', 'SR Watson', 'AT Rayudu', 'KM...  AK Chaudhary
392202   ['RJ Quiney', 'GC Smith', 'SA Asnodkar', 'RA J...    GAV Baxter
1254071  ['DA Warner', 'JM Bairstow', 'KS Williamson', ...  K Srinivasan

             Umpire2
ID
419150   SK Tarapore
419118     RB Tiffin
1216516   PR Reiffel
392202   RE Koertzen
1254071  Nitin Menon

In [14]:
#info()
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

In [15]:
#describe()
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [16]:
#isnull()
print(movies.isnull())
print(movies.isnull().sum())

      title_x  imdb_id  poster_path  wiki_link  title_y  original_title  \
0       False    False        False      False    False           False
1       False    False         True      False    False           False
2       False    False        False      False    False           False
3       False    False        False      False    False           False
4       False    False         True      False    False           False
...       ...      ...          ...        ...      ...             ...
1624    False    False        False      False    False           False
1625    False    False        False      False    False           False
1626    False    False         True      False    False           False
1627    False    False        False      False    False           False
1628    False    False        False      False    False           False

      is_adult  year_of_release  runtime  genres  imdb_rating  imdb_votes  \
0        False            False    False   False        False       False
1        False            False    False   False        False       False
2        False            False    False   False        False       False
3        False            False    False   False        False       False
4        False            False    False   False        False       False
...        ...              ...      ...     ...          ...         ...
1624     False            False    False   False        False       False
1625     False            False    False   False        False       False
1626     False            False    False   False        False       False
1627     False            False    False   False        False       False
1628     False            False    False   False        False       False

      story  summary  tagline  actors  wins_nominations  release_date
0     False    False     True   False             False         False
1     False    False     True   False              True         False
2     False    False     True   False              True         False
3     False    False     True   False              True         False
4     False    False     True   False             False         False
...     ...      ...      ...     ...               ...           ...
1624  False    False     True   False              True         False
1625  False    False     True   False              True         False
1626  False    False     True   False              True          True
1627  False    False     True   False              True         False
1628  False    False     True   False              True         False

[1629 rows x 18 columns]
title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [17]:
#duplicated
movies.duplicated()
print(movies.duplicated().sum())

0

In [19]:
student_dict = {
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [21]:
#rename----rename column name
students.rename(columns={'marks': 'percentage'}, inplace=True)
students

    iq  percentage  package
0  100          80       10
1   90          70        7
2  120         100       14
3   80          50        2
4    0           0        0
5    0           0        0

In [22]:
#Maths Methods
#sum-- perform sum operation on all columns 
students.sum()

iq            390
percentage    300
package        33
dtype: int64

In [23]:
#columnwise sum
students.sum(axis=0)

iq            390
percentage    300
package        33
dtype: int64

In [24]:
#rowwise sum--axis parameter
students.sum(axis=1)

0    190
1    167
2    234
3    132
4      0
5      0
dtype: int64

In [20]:
#mean--mean columnwise  
students.mean()

#mean--mean rowwise  
students.mean(axis=1)

0    63.333333
1    55.666667
2    78.000000
3    44.000000
4     0.000000
5     0.000000
dtype: float64

In [18]:
#min--min columnwise  
students.min()

iq            0
percentage    0
package       0
dtype: int64

In [19]:
#max--max columnwise  
students.max()

iq            120
percentage    100
package        14
dtype: int64