In [1]:
import numpy as np
import pandas as pd

In [2]:
# apply(series + dataframe)
temp = pd.Series([10,20,30,40,50])

temp

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
def sigmoid(value):
  return 1/1+np.exp(-value)

In [4]:
temp.apply(sigmoid)

0    1.000045
1    1.000000
2    1.000000
3    1.000000
4    1.000000
dtype: float64

In [5]:
points_df = pd.DataFrame(
    {
        '1st point':[(3,4),(-6,5),(0,0),(-10,1),(4,5)],
        '2nd point':[(-3,4),(0,0),(2,2),(10,10),(1,1)]
    }
)

points_df

  1st point 2nd point
0    (3, 4)   (-3, 4)
1   (-6, 5)    (0, 0)
2    (0, 0)    (2, 2)
3  (-10, 1)  (10, 10)
4    (4, 5)    (1, 1)

In [6]:
def euclidean(row):
  pt_A = row['1st point']
  pt_B = row['2nd point']

  return ((pt_A[0] - pt_B[0])**2 + (pt_A[1] - pt_B[1])**2)**0.5

In [8]:
points_df['distance'] = points_df.apply(euclidean,axis=1)
points_df

  1st point 2nd point   distance
0    (3, 4)   (-3, 4)   6.000000
1   (-6, 5)    (0, 0)   7.810250
2    (0, 0)    (2, 2)   2.828427
3  (-10, 1)  (10, 10)  21.931712
4    (4, 5)    (1, 1)   5.000000

In [9]:
# isin(series)
import pandas as pd

# Your main DataFrame
df = pd.DataFrame({
    'player': ['V Kohli', 'MS Dhoni', 'RG Sharma', 'G Maxwell'],
    'team': ['RCB', 'CSK', 'MI', 'RCB']
})

# The Series containing values you want to match
selected_players = pd.Series(['V Kohli', 'RG Sharma'])

# Filter the DataFrame
filtered_df = df[df['player'].isin(selected_players)]
print(filtered_df)

      player team
0    V Kohli  RCB
2  RG Sharma   MI

#insert()

#The df.insert() method in pandas is used to insert a single new column into a DataFrame at a specific, designated index position.

By default, when you assign a new column using df['new_col'] = values, pandas always appends it to the very end (the far right). df.insert() allows you to place it exactly where you want (e.g., as the very first column).

df.insert(loc, column, value, allow_duplicates=False)

In [10]:
# Sample DataFrame
df = pd.DataFrame({
    'player': ['V Kohli', 'MS Dhoni'],
    'runs': [12000, 10000]
})

# Insert a 'team' column at index position 1 (between 'player' and 'runs')
df.insert(1, 'team', ['RCB', 'CSK'])

print(df)

     player team   runs
0   V Kohli  RCB  12000
1  MS Dhoni  CSK  10000

In [14]:
# copy(series + dataframe)

#The df.copy() method in pandas is used to create a completely independent clone of a DataFrame or a Series.
#df.copy(deep=True)

df1 = pd.DataFrame({'A': [1, 2, 3]})
df2 = df1.copy()  # Creates a totally independent clone

df2['A'] = [99, 99, 99]

print(df1['A'].tolist())  
# Output: [1, 2, 3] <-- Safe! df1 remains untouched.
print(df2['A'].tolist())

[1, 2, 3]
[99, 99, 99]